version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  musicapp-api:
    build:
      context: ./MusicAppAPI
      dockerfile: Dockerfile
    ports:
      - "5064:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - DB_USER=deepinnothing
      - DB_PASSWORD=pass123
      - DB_NAME=music_store
      - JWT_KEY=super-duper-secret-jwt-key-1234567890
    depends_on:
      - rabbitmq
    networks:
      - app-network

  musicapp-analytics:
    build:
      context: ./MusicAppAnalytics
      dockerfile: Dockerfile
    ports:
      - "5048:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
volumes:
  rabbitmq_data: